### ISSUE TITLE
Preview does not honor the folder icon matrix opacity setting

### ISSUE THREAD

**Issue by enaloha** [AnemoneTeam/Anemone#152] opened 2016-08-30 00:45 UTC
Yeah, it's a minor cosmetic issue, but since Anemone strives for perfection, this might still get fixed with a low priority status. I am attaching a screenshot demonstrating that the icon matrix of folders is overlaid on custom folders even if the matrix is set to full transparency.

![img_0955](https://cloud.githubusercontent.com/assets/13284542/18072036/721ff14e-6df6-11e6-80e3-1a1d7110acc4.JPG)

While we're at the preview, I am also attaching a screenshot of the original appearance. In a perfect world, the icons in the preview would be slightly adjusted downward and spaced a little more tightly. Again, this is really extreme nitpicking and really minor.

![img_1231](https://cloud.githubusercontent.com/assets/13284542/18072086/0b0ea5da-6df7-11e6-9b0a-0d8c123ff8e8.jpg)

Please keep up the good work. And I was wondering if and how I can join the slack group. Please let me know.

**Comment by coolstar** [comment] 2016-08-30 00:51
Duplicate of #150

**Closed as completed by coolstar** 2016-08-30 00:51 UTC

**Comment by enaloha** [comment] 2016-08-30 01:39
Sorry. How did I miss that?
