### ISSUE TITLE
9.3.3 safe mode

### ISSUE THREAD

**Issue by hip5** [AnemoneTeam/Anemone#110] opened 2016-08-05 21:42 UTC
New JB on 9.3.3 running no tweaks or themes, nightly build of anemone 356 once phone goes to sleep mode when waking back up goes direct to safe mode. I am on a 6S when I take anemone off JB works great.Crash reporter just says springboard crashed no errors with it.Ran Icleaner pro numerous times also Please help I miss my themes.

Peace out,@hip5

**Comment by hip5** [comment] 2016-08-05 22:17
Just restored while apple is still signing 9.3.3. Still would like to know if their ideas as to what may have happened

**Comment by coolstar** [comment] 2016-08-12 22:08
It seems it's a conflict with another tweak. Are you still getting the issue?

**Comment by EricG24** [comment] 2016-08-12 23:29
I'm having this same issue on my iPhone 6. Everytime I go to lock and then try to unlock I'm in safe mode. I have only like 4 tweaks don't know what could be causing this issue?

**Comment by hip5** [comment] 2016-08-13 00:55
I did a restore and that fixed it for me. Make sure you read before you do this so you don't loose JB,MAKE SURE YOU DONT UPGRADE TO 9.3.4

**Comment by gameking30578** [comment] 2016-08-13 08:00
I've spend literally the past 4 hours going through other recently installed tweaks and looking what could be the problem for me. Anemone version 368 causes my phone to safe mode when I lock it. Have downgraded to 345 until it's fixed

**Comment by BlurrX** [comment] 2016-08-13 09:54
I have to reboot and lose all 27 of my tweaks because Anemone is bugging out? I really hope it's worth it and it better fix it

**Comment by Minix105** [comment] 2016-08-18 01:01
This is happening to me to but I don't know what to do at all plz help

**Comment by coolstar** [comment] 2016-08-20 02:30
Workaround for now: use iCleaner to disable AnemoneDock.dylib

we haven't been able to re-produce the issue on our end yet. For now you may use this workaround until we can get a proper fix.

**Comment by gameking30578** [comment] 2016-08-20 02:40
I will try that tonight.
How else can we help? And  just thought of this... I have a tweak for 5 icons in the dock. Could that be interfering?

**Comment by coolstar** [comment] 2016-08-20 02:41
If you could use crashreporter and get me a crash report I can try seeing if I can get some useful info from it.

If not I can send you some new versions of AnemoneDock.dylib to test

**Comment by gameking30578** [comment] 2016-08-20 02:43
I'm on it. Currently on the phone with my CC company. As soon as I'm done I'll try it and send logs

**Comment by gameking30578** [comment] 2016-08-20 03:41
Crash log sent with all settings enabled.
Disabled AnemoneDock.dylib and no crashes

**Comment by coolstar** [comment] 2016-08-20 18:29
Are you still experiencing the issue with the latest nightly? I made some changes to the dock theming; wonder if those helped.

If not, I'll need someone who I can chat with on skype who's willing to test new AnemoneDock.dylib's

**Comment by gameking30578** [comment] 2016-08-20 18:36
Same issue with version 375. I can help tonight if you don't find someone earlier.

**Comment by gameking30578** [comment] 2016-08-21 01:31
Do you still need someone to test the dock dylibs?

**Comment by tecateo** [comment] 2016-08-21 05:02
I found out that if I enable "reduce transparency" (settings>general>accesibility>increase contrast>reduce transparency) I can reproduce the crashes (while I have AnemoneDock.dylib enabled). So I disabled AnemoneDock.dylib and enabled reduce transparency without any issues. I think that happens because the low power mode enables the reduce transparency. So when you lock the phone or something it enters in low power mode and Voila! Springboard crashes.

**Comment by coolstar** [comment] 2016-08-21 08:17
Seems like it is indeed reduce transparency. As per @tecateo's note, I enabled reduce transparency here and was able to re-pro the issue on my device.

**Comment by coolstar** [comment] 2016-08-21 08:41
This issue has been fixed in 1.1-376

**Comment by tecateo** [comment] 2016-08-21 16:54
I'm still able to re-pro the crash with reduce transparency, but this time i haven't disabled AnemoneDock.dylib, instead I check/uncheck some options on Anemone. The options that change/modify the dock's background allow me to re-pro the crash, so when I haven't check any option that involve dock's background (no dock in anemone or change the background because of a theme) the reduce transparency works good, but when I check some dock's background options and then I go to enable the reduce transparency I can enable and disable the switch many times I want without any problem, but when I'm going to the main screen to see the dock I got a crash instantly. By the way I'm on ios 8.4

**Comment by coolstar** [comment] 2016-08-21 18:58
@tecateo yeah 376 specifically fixes the crash with sleep/waking the device with reduce transparency enabled, not toggling the setting itself

**Comment by tecateo** [comment] 2016-08-21 21:20
@coolstar thanks for your efforts to fix this issue, you're doing a really great job! I meant that the problem was keep the reduce transparency activated and then go to see the dock in the app drawer while in anemone you have some dock's background modification that re-pro the crashes

**Comment by Minix105** [comment] 2016-08-22 20:16
So what do I do I'm new to jailbraking and do not know a lot so do I use Cydia eraser and then Rejailbrake after or do I just use Icleaner if I need to use icleaner plz tell me how if none of this is needed plz tell me and I will go get the tweak thank you a lot for the help.

**Comment by Minix105** [comment] 2016-08-22 20:22
Ok so here is what I got now when I try to get the tweak is says that is was not finding the file for the tweak and that u wold have to  manually fix it but I don't know how to do this I'm not that smart 😂 but I do need help real bad plz help me 😔

**Comment by Minix105** [comment] 2016-08-22 20:26
Ok I do have a crash log if you need it here it is

**Comment by Minix105** [comment] 2016-08-22 20:26
https://ghostbin.com/paste/vtapc

**Comment by Minix105** [comment] 2016-08-22 20:30
One more thing I did manage to get the tweak just now and it is still putting me in safe mode when I lock my phone I don't know what to do so pleas keep me up to date Thank You !

**Comment by coolstar** [comment] 2016-08-27 18:43
Fixed in 1.1-396

**Closed as completed by coolstar** 2016-08-27 18:43 UTC
Labels: bug

**Comment by Minix105** [comment] 2016-08-28 17:25
When will this come out
