### ISSUE TITLE
Crashes my springboard 

### ISSUE THREAD

**Issue by Minix105** [AnemoneTeam/Anemone#126] opened 2016-08-17 23:51 UTC
Every time I put my phone in sleep mode it goes to safe mode and says springboard crashed and i know it was Anemone because when I deleted it it worked fine I hope you can help me because I want to use this tweak real bad and in on an iPhone 6s Plus if you need to know and thx hope you can fix this

**Comment by Minix105** [comment] 2016-08-18 00:13
Sry for the type o meant to say I'm

**Comment by coolstar** [comment] 2016-08-20 02:27
Duplicate of #110

**Closed as completed by coolstar** 2016-08-20 02:27 UTC
Labels: duplicate

**Comment by shawn954** [comment] 2016-08-20 02:28
Yeah I'm having the same problem. It really sucks cause this the only theme app they got for using themes and it isn't working right.

**Comment by coolstar** [comment] 2016-08-20 02:30
Please don't make any additional comments here. The issue is being tracked at #110
