### ISSUE TITLE
Classic Dock themes not working

### ISSUE THREAD

**Issue by MikeyScene420** [AnemoneTeam/Anemone#73] opened 2015-12-22 02:45 UTC
Latest update won't theme the dock. Tested with iPhone 6 Plus on 9.0.2

**Comment by LaCh0uine** [comment] 2016-01-05 16:57
Any news about this ?

**Comment by coolstar** [comment] 2016-01-06 22:40
Modern mode docks still work fine. Classic mode dock themes seem to be having issues. We are investigating the cause of this bug.

**Comment by LaCh0uine** [comment] 2016-01-07 14:29
@coolstar Is it easy to convert classicdock to modern ?

**Comment by coolstar** [comment] 2016-01-07 16:25
@LaCh0uine yes, it is

**Comment by coolstar** [comment] 2016-01-31 18:45
Fixed in 1.1-138.

**Closed as completed by coolstar** 2016-01-31 18:45 UTC
Labels: bug
