### ISSUE TITLE
The same color for clock hands

### ISSUE THREAD

**Issue by AX3L4** [AnemoneTeam/Anemone#208] opened 2017-02-25 18:14 UTC
Why does anemone not theme the clock icon's hands correctly? I have the same color for all the clock hands. E.g: i use pink for the minutes and the hours and violet for the seconds but now all of the hands are pink

**Comment by coolstar** [comment] 2017-06-03 18:20
Duplicate of #202

**Closed as completed by coolstar** 2017-06-03 18:20 UTC
Labels: duplicate
