### ISSUE TITLE
Label shadows not working.

### ISSUE THREAD

**Issue by kaebiene** [AnemoneTeam/Anemone#34] opened 2015-10-18 21:31 UTC
I saw on the wiki that for anemone, the code had changed for label shadows (https://github.com/AnemoneTeam/Anemone/wiki/Icon-Labels#example-plist) so I tried it out in a plist yet there's no change at all. Cydia tweaks such as Classic Labels for iOS 7.1 & 8 don't work enough unless used with Winterboard.

**Comment by coolstar** [comment] 2015-10-18 23:21
Looks like there's a bug in the shadow renderer. To workaround it for now set a shadow color.

**Comment by coolstar** [comment] 2015-10-26 04:35
Edit: the shadow color needs to be set. The Example has one set. Odd it isn't working for you. I'll try it and see right now.

**Comment by coolstar** [comment] 2015-11-01 03:22
ok I've confirmed the bug here. Working on a fix.

**Comment by coolstar** [comment] 2015-11-01 04:46
Fixed in Anemone 1.1-38 on the fast ring repo.

**Closed as completed by coolstar** 2015-11-01 04:46 UTC
Labels: bug

**Comment by kaebiene** [comment] 2015-11-01 11:04
Thank you! Since you've updated ClassicLockScreen, my setup is complete now <3
