### ISSUE TITLE
Random freezing/reboots on iPhone 6/6+ on iOS 10

### ISSUE THREAD

**Issue by kron1k** [AnemoneTeam/Anemone#196] opened 2017-02-07 21:45 UTC
I'm on yalu102/6+. My phone will work for about 5 mins then freeze up and either crash and reboot or I have to hard reset. I have maybe 10 tweaks installed at the moment the only time I get errors and these issues is with Anemone installed. I really don't want to go back to winterboard. I can't keep Anemone installed though because if keeps making me reboot.

**Comment by coolstar** [comment] 2017-02-16 05:44
Confirmed the issue here on my iPhone 6, iOS 10. For anyone affected by this issue, please try this "AnemoneLite" deb and let me know if it is stable for you: https://www.dropbox.com/s/dgd40skjcr28f2y/com.anemonetheming.anemone_2.1.1-18_iphoneos-arm.deb?dl=1

There are some features missing in that version, however that is the point, to try and isolate the culprit portion of Anemone.

**Comment by kr0n1k** [comment] 2017-02-16 07:21
Seems to be stable. Ill give it a test run and see what happens and report back in the morning

**Comment by coolstar** [comment] 2017-02-16 09:03
Updated build with a few optimizations: https://www.dropbox.com/s/zoyiv595yx371ek/com.anemonetheming.anemone_2.1.1-21_iphoneos-arm.deb?dl=0

Shouldn't make a difference with the amount stripped down in these AnemoneLite builds, but just to make sure any bugs from the future builds don't affect this issue.

**Comment by kr0n1k** [comment] 2017-02-16 13:55
The -21 version is working perfectly here. No crashes

**Comment by coolstar** [comment] 2017-02-16 18:47
Alright cool. Yeah 21 was running quite stable here, so here's 22 with more components of Anemone enabled: https://www.dropbox.com/s/8ufphnn1929ez7i/com.anemonetheming.anemone_2.1.1-22_iphoneos-arm.deb?dl=0

let me know how it runs for you

**Comment by kr0n1k** [comment] 2017-02-16 19:21
It froze up my phone twice and had to reboot. Downgraded back to -21 again

**Comment by coolstar** [comment] 2017-02-16 19:25
Interesting... I removed some components on 23 so let's see if this makes it more stable https://www.dropbox.com/s/px5z46pwx9rlm7v/com.anemonetheming.anemone_2.1.1-23_iphoneos-arm.deb?dl=0

**Comment by kr0n1k** [comment] 2017-02-16 20:12
Unfortunately -23 caused reboots as well. After installing it froze on the respring spinner and I had to reboot. Then it worked for a bit till my phone crashed.

**Comment by OVERL0AD-Dan** [comment] 2017-02-16 20:29
Sorry I was busy at work, -18 from yesterday ran flawlessly. I just installed-23 so well see how it goes. Oh coolstar btw, all versions cause a crash or respring after using my CarPlay radio. Like after I turn off the car and unplug the phone. Just thought you would want to know.

**Comment by OVERL0AD-Dan** [comment] 2017-02-17 16:30
So far -23 is running good, no crashes for me. And the last 2 times I've used my CarPlay radio it didn't crash either.

**Comment by kr0n1k** [comment] 2017-02-17 19:13
I just tried it again and my screen froze on the springboard 😞😞

**Comment by kr0n1k** [comment] 2017-02-18 00:10
I really hope this can be figured out. I miss my ui

**Comment by kr0n1k** [comment] 2017-02-18 00:52
Here's a tweak list if it helps.

7-zip (POSIX): 4.57-3p
Activator: 1.9.12
Anemone: 2.1.1-21
AnotherLockKeyboard: 0.0.3.2
Apex 2 (iOS 7,8,9): 1.6.1
App Admin: 1.0r-68
AppList: 1.5.13
APT 0.6 Transitional: 1:0-23
APT 0.7 (apt-key): 0.7.25.3-3
APT 0.7 Strict (lib): 0.7.25.3-14
APT 0.7 Strict: 0.7.25.3-8
Base Structure: 1-4
Berkeley DB: 4.6.21-5
BigBoss Icon Set: 1.0
Bloard: 0.1.2-1
Bourne-Again SHell: 4.0.44-16
BrowserBreadcrumbCleanup: 2.0-1
bzip2: 1.0.5-8
CCRecord: 0.0.1-4
Cephei: 1.10
ClearNotificationsOneTapPlz: 1.1.0
ColorBadges: 1.1.2-1
Core Utilities (/bin): 8.12-9
Core Utilities: 8.12-13
CrashReporter: 1.15.0-1
Cream 2: 1.1-1
Cydia Installer: 1.1.30
Cydia Substrate: 0.9.6301
Cydia Translations: 1.1.12
Darwin Tools: 1-5
Date In Statusbar: 0.9.1-2
Debian Packager: 1.18.10-12
Debian Utilities: 3.3.3ubuntu1-1p
Diff Utilities: 2.8.1-6
diskdev-cmds: 421.7-4
DoubleCut: 0.4.1-1
ExtraIconDock: 0.1.0
file-cmds: 220.7-3
Filza File Manager: 3.3.2
Find Utilities: 4.2.33-7
Flame: 1.3
Flex 3: 3~EarlyAccess3
Flipswitch: 1.0.15
FolderEnhancer (iOS 7/8/9/10): 2.13.0
GNU Privacy Guard: 1.4.8-4
grep: 2.5.4-3
gzip: 1.6-7
HideLabels10: 1.0
iCleaner Pro: 7.6.1~beta1
IconSupport: 1.10.0.2-1
iOS Firmware: 10.2
iPhone Firmware (/sbin): 0-1
KarenLocalizer: 1.0
KarenPrefs: 1.0.1
LastApp: 1:1.4.0-1
libcolorpicker: 1.6-1
libcrashreport: 1.1.0-1
libmoorecon: 0.9.9.0~beta4-1
libpackageinfo: 1.1.0.1-1
libsymbolicate: 1.9.0-1
Link Identity Editor: 1:1.2.1
LZMA Utils: 4.32.7-5
mikoto: 3.0.8
Minimal Hosts Blocker: 7.3
New Curses: 5.7-15
Noctis (iOS 10): 1.9
NoLSPadLock: 0.1
NoSlowAnimations: 5.2.1
OpenNotifier10 - tateu: 2.5.0~beta1+debug
PAM (Apple): 32.1-4
PAM Modules: 36.1-5
Patcyh: 1.2.0
Phantom (Lite) for Snapchat: 5.3.1-4
Photo Tools: 1.3
pincrush: 0.9.2-1
PreferenceLoader: 2.2.4~alpha1
PreferenceOrganizer 2: 3.7
Profile Directory: 0-2
readline: 6.0-8
RocketBootstrap: 1.0.5
RoundDock: 1.1.1-1
RunMario: 0.1
SameStatusBar: 0.0.1
sed: 4.1.5-8
SendDelay: 1.4-7
shell-cmds: 118-7
Snapper 2: 1.2.5
Sonus: 2.0.0-1+debug
Substrate Safe Mode: 0.9.6001
SwipeSelection: 1.5.2-1
system-cmds: 433.8-14
Tage: 1.2.2
Tape Archive: 1.29-10
TechSupport Framework: 1.5.0.1-1
uasharedtools: 2.1r-46
UIKit Tools: 1.1.12
Unify: 1.1.1.6
unrar: 3.6.8-2p
unzip: 5.52-5p
VideoPane: 2.0.6
zip: 2.32-5p

**Comment by coolstar** [comment] 2017-02-18 01:37
I haven't seen any crashes here either... not sure what's wrong on your device @kr0n1k

**Comment by kr0n1k** [comment] 2017-02-18 01:38
:( should I try disabling the theme?

**Comment by coolstar** [comment] 2017-02-18 01:38
yes

**Comment by kr0n1k** [comment] 2017-02-18 02:02
Well it looks like it's the theme. However it doesn't say it's not compatible with Anemone when I open Anemone. I am using a theme from iOS 8 and it was originally a winterboard theme. This last week I changed it to an IconBundles theme so it'd work on 10.2. Could I send you my theme to see what's causing the crash. I thought it should work as I followed a tutorial.

**Comment by coolstar** [comment] 2017-02-18 02:03
yeah, you can send it and I can take a look

**Comment by kr0n1k** [comment] 2017-02-18 02:24
Which email do you want me to send it to

**Comment by kr0n1k** [comment] 2017-02-18 02:28
https://www.dropbox.com/s/ud8v45ugmrfhyt1/theme.zip?dl=0

**Comment by kr0n1k** [comment] 2017-02-18 03:09
Seems to be the anemoneeffects folder

**Comment by kr0n1k** [comment] 2017-02-18 07:29
I've had no crashes on -23 after disabling my ui theme

**Comment by coolstar** [comment] 2017-02-18 07:33
Give this version a try and see how it runs for both of you: https://dl.dropboxusercontent.com/u/59964215/iOS/com.anemonetheming.anemone_2.1.1-26_iphoneos-arm.deb

**Comment by kr0n1k** [comment] 2017-02-18 07:49
Have you looked at my theme yet? Something with either the AnemoneEffects folder or UI theme causes it. I have my icon theme working.

I will try -26 and report back.

Thanks again Coolstar I appreciate this more than you know.

**Comment by OVERL0AD-Dan** [comment] 2017-02-18 12:06
Installed-26 about an hour ago, so far it seems stable but it did crash after my CarPlay radio was shut off again. -23 didn't do that. I'll keep using it and see how it is through a longer test.

**Comment by kr0n1k** [comment] 2017-02-18 13:56
I've been using-26 and it works fine unless I enable my ui theme. Once I do that my phone starts to lock up. Otherwise it's running smoothly. 

If you could look into my ui theme and let me know coolstar I'd greatly appreciate it. I moved the AnemoneEffects folder to that theme as well so I don't know why it's happening.

**Comment by kr0n1k** [comment] 2017-02-19 17:04
So is are ui themes not compatible with Anemone or what's going on. I get no crashes when it's disabled. I removed almost everything from it except status bar images

**Comment by OVERL0AD-Dan** [comment] 2017-02-19 17:55
Dude he's probably busy, give him some time man it's not like he has to even fix it. I'm only getting booted into safe mode after using my CarPlay radio now. But yea chill out and be patient lol, coolstar's a cool guy, I'm sure he'll get to the bottom of it eventually;)

**Comment by kr0n1k** [comment] 2017-02-19 17:59
I know I just get sick to my stomach when I get rebooted as I'm very wary about these semi-tethered jbs. I came from 8.4 which I loved so much. I just don't want to fuck up my jb because I don't know what I'd do with my phone if it was stock.

**Comment by gmawji** [comment] 2017-02-19 18:09
UI themes are fine. I run one of the most covered UI themes and have zero issues. AnemoneEffects are fine also for me.

**Comment by gmawji** [comment] 2017-02-19 18:18
Right I've looked at your theme and I think after this comment CS will most likely close this issue.
Your issue that, while Anemone does not complain about the theme; your theme posted here **(which you should remove because it's a paid theme)** is not an iOS10 or Anemone theme, therefore it still isn't really compatible.

I know there are multiple copies of this port floating around but your port has a lot of bad image files and files which shouldn't even be in there. See Screenshot:

<img width="572" alt="screenshot 2017-02-19 13 13 17" src="https://cloud.githubusercontent.com/assets/7138919/23104943/53dcd9a8-f6a5-11e6-9988-730922cf44dd.png">

The files beginning with '-' and the .png1 and files that don't show an image preview are corrupted files.

The AnemoneEffects in this folder is for @3x only. If you don't have a plus device it won't work.

Another thing, the com.apple.accountsui folder has an item called dataclassIconCache@2x.artwork. That will make your device crash whenever you open settings -> icloud. That file is unnecessary unless you are manually theming.

<img width="595" alt="screenshot 2017-02-19 13 16 01" src="https://cloud.githubusercontent.com/assets/7138919/23104974/b7e41b6e-f6a5-11e6-87f2-a341137de8d5.png">

**Comment by kr0n1k** [comment] 2017-02-19 18:26
Ok well again I purchased the theme so I'm free to use it as I please. How is it not correctly updated for Anemone? I switched the icons to IconBundles and updated the plist.

As for the UI theme the images ending in png1 is just to make that file not show up as I didn't like that part of the theme. I've actually deleted all of the UI theme Bundles except for AppStore springboard and Cydia. As id like to use the icon badges. I'll go through and delete those files since I don't plan on using the images.

As for the AnemoneEffects folder I'm on a 6+ which is why I have the @3x. 

The only reason I posted the theme is so coolstar could look it over. Once he did I was going to remove it from my Dropbox folder.

**Comment by gmawji** [comment] 2017-02-19 18:30
I never said your not free to use it as you please. If you bought it, then it's yours to do whatever aside from give it to people. It doesn't mean you've converted it properly though.

You still have files in there that will make it crash. If the UI theme is what is causing the issue then you know that the theme is the issue rather than Anemone.

Have you tried a different UI theme?

**Comment by kr0n1k** [comment] 2017-02-19 18:32
No I haven't I was just wondering if someone would go through it and look at which files are causing the crash as I want my Bluetooth and location icons. That and my AnemoneEffects otherwise the rest i don't really care for.

**Comment by coolstar** [comment] 2017-02-21 05:52
Fixed in 1.1-26

**Comment by coolstar** [comment] 2017-02-21 05:53
Fixed in 2.1.1-26

**Closed as completed by coolstar** 2017-02-21 05:53 UTC
Labels: bug

**Comment by coolstar** [comment] 2017-02-21 05:54
The CarPlay issue is separate, so @OVERL0AD-Dan I'll make a new issue for that.

**Comment by kr0n1k** [comment] 2017-02-21 06:00
But my phone still freezes when I apply an anemone effect

**Comment by coolstar** [comment] 2017-02-21 06:01
I'm using CircleIcons here with no issues, your theme has corrupted images.

**Comment by kr0n1k** [comment] 2017-02-21 06:03
I made a theme with just the AnemoneEffects folder and a iphoneOverlay@3x png and it froze. I'm not using the us theme anymore

**Comment by coolstar** [comment] 2017-02-21 06:04
Making a theme with only 3x is *not* valid. You need both 2x and 3x images.

**Comment by kr0n1k** [comment] 2017-02-21 06:07
Ok I didn't realize this. The wiki doesn't really explain it like that. That's one thing that's tough for people getting into theme building to know. I will edit it and see what happens. Sorry to bug you I just really want Anemone to work for my theme .

**Comment by kr0n1k** [comment] 2017-02-21 18:57
I removed flip switch and Activator and the freezing and crashes have stopped
